name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Nginx version (optional, if not provided will be auto-detected)'
        required: false
        type: string

env:
  IMAGE_NAME: nginx

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: debian
            branch: stable
            install_pkgs: apt-get update && apt-get install -y --no-install-recommends build-essential git libpcre3-dev libssl-dev zlib1g-dev libbrotli-dev wget
          - platform: debian
            branch: mainline
            install_pkgs: apt-get update && apt-get install -y --no-install-recommends build-essential git libpcre3-dev libssl-dev zlib1g-dev libbrotli-dev wget
          - platform: alpine
            branch: stable
            install_pkgs: apk add --update --no-cache build-base git pcre-dev openssl-dev zlib-dev linux-headers brotli-dev
          - platform: alpine
            branch: mainline
            install_pkgs: apk add --update --no-cache build-base git pcre-dev openssl-dev zlib-dev linux-headers brotli-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        id: get_version
        if: ${{ !inputs.version }}
        run: |
          if [ "${{ matrix.platform }}" = "debian" ]; then
            IMAGE="nginx:${{ matrix.branch }}"
          else
            IMAGE="nginx:${{ matrix.branch }}-${{ matrix.platform }}"
          fi
          echo "version=$(docker pull $IMAGE > /dev/null && docker inspect $IMAGE |grep NGINX_VERSION |head -n 1|sed 's/                "NGINX_VERSION=//g' | sed 's/",//g')" >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/nginx-brotli
          tags: |
            # 手动输入版本时只输出版本号
            type=raw,value=${{ inputs.version }},enable=${{ inputs.version && matrix.platform == 'debian' }}
            type=raw,value=${{ inputs.version }}-${{ matrix.platform }},enable=${{ inputs.version && matrix.platform != 'debian' }}
            # 自动检测版本时使用完整的semver格式
            type=semver,pattern={{version}},value=${{ steps.get_version.outputs.version }},enable=${{ !inputs.version && matrix.platform == 'debian' }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.get_version.outputs.version }},enable=${{ !inputs.version && matrix.platform == 'debian' }}
            type=raw,value=${{ matrix.branch }},enable=${{ !inputs.version && matrix.platform == 'debian' && matrix.branch != 'mainline' }}
            type=raw,value=latest,enable=${{ !inputs.version && matrix.platform == 'debian' && matrix.branch == 'mainline' }}
            # 其它平台（如alpine）自动检测版本
            type=semver,pattern={{version}}-${{ matrix.platform }},value=${{ steps.get_version.outputs.version }},enable=${{ !inputs.version && matrix.platform != 'debian' }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.platform }},value=${{ steps.get_version.outputs.version }},enable=${{ !inputs.version && matrix.platform != 'debian' }}
            type=raw,value=${{ matrix.branch }}-${{ matrix.platform }},enable=${{ !inputs.version && matrix.platform != 'debian' && matrix.branch != 'mainline' }}
            type=raw,value=${{ matrix.platform }},enable=${{ !inputs.version && matrix.platform != 'debian' && matrix.branch == 'mainline' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NGINX_IMAGE=nginx:${{ inputs.version || steps.get_version.outputs.version }}${{ matrix.platform != 'debian' && format('-{0}', matrix.platform) || '' }}
            NGINX_VERSION=${{ inputs.version || steps.get_version.outputs.version }}
            INSTALL_PKGS=${{ matrix.install_pkgs }}
